name: 'Notion release notes'
description: 'Creates a new page in an existing database to capture release notes'
branding:
  icon: type
  color: green
inputs:
  token:
    description: 'Notion API token'
    required: true    
  database:
    description: 'Parent database to add to'
    required: true    
  notes:
    description: 'Name for the release'
    required: true
  owner:
    description: 'Owner for the release'
    required: true
  repoTags:
    description: 'Comma separated tag list: Repo for the release'
    required: true
  envTags:
    description: 'Comma separated tag list: Env for the release'
    required: true
  verifiedTags:
    description: 'Comma separated tag list: Verification status for the release'
    required: true
  body:
    description: 'Body content for release notes'
    required: true
outputs:
  status: 
    description: 'The status of the update'
runs:
  using: 'node12'
  main: 'dist/index.js'